### ISSUE TITLE
Code consultation

### ISSUE THREAD

**Issue by LiHebai** [justin5718/FL_WIKI#1]
https://github.com/UbiquitousLearning/End2end-Federated-Learning/issues/5
I have seen the problem you mentioned in this project, and I have also encountered the same problem now, may I ask how you solve it

**Comment by justin5718** [comment]
Thank you for reaching out. Regarding the issue you mentioned, I encountered the same challenge as well. At the time, I needed more detailed code from the repository owner, so I decided to not pursue solving the problem further. Thank you for your inquiry, and I hope you find a solution.

**Comment by destinyson** [comment]
I'm terribly sorry for your long-time waiting T_T. I was trying to find job for a year...
I will update readme and add source code this evening. Sorry for your waiting again.

**Comment by destinyson** [comment]
I'm terribly sorry for your long-time waiting T_T. I was trying to find job for a year...
I will update readme and add source code this evening. Sorry for your waiting again.

**Comment by LiHebai** [comment]
Thank you very much for your reply.

**Comment by justin5718** [comment]
Please discuss this issue in the corresponding project, closed
